### PR TITLE
Use packageName in Relay header

### PR DESCRIPTION
**Pull request by jakubuid**

### CODE REVIEW

**Comment by jakubuid** [comment]
@Cali93 @heilhead can you please review?

**Comment by Cali93** [comment]
@jakubuid  I'll try to take some time EoW/early next week to come to a resolution for the whole issue.

**Comment by heilhead** [comment]
@jakubuid Sorry, I'm a bit out of context for these changes. Let's wait for @Cali93 to come up with a better spec for the suggested fix, and will pick this up then.

**Review by Cali93 — APPROVED** [review]
Perfect, thanks and sorry for the huge delay.

**Pull request merged**
